version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_NAME=miproyecto
      - SECRET_KEY=mysecretkey
    depends_on:
      - db
    command: ["bash", "-c", "./wait-for-it/wait-for-it.sh db:3306 -- python app.py"]

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"  
      MYSQL_DATABASE: miproyecto
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

volumes:
  db_data: